In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Load the dataset
df_bcn = pd.read_csv('/workspaces/ABC-final-project/src/data/barcelona_2015_2026.csv', sep=',', engine='python')

In [6]:
df_bcn.head()

,ndvi,ndbi,lst_celsius,elevation,longitude,latitude,fecha
0,0.104949,0.141052,36.740617,187,2.153994,41.421864,2016-07-17
1,0.275537,0.061476,34.693557,7,2.085892,41.334321,2016-07-17
2,0.083277,0.167822,37.000677,58,2.118558,41.375535,2016-07-17
3,0.725166,-0.147893,29.298013,272,2.098252,41.446837,2016-07-17
4,-0.032787,-0.113208,38.393443,0,2.254149,41.404057,2016-07-17

In [36]:
df_renta.head()

,Municipios,Distritos,Secciones,Indicadores de renta media y mediana,Periodo,Total
0,08001 Abrera,NaN,NaN,Renta neta media por persona,2023,16.682
1,08001 Abrera,0800101 Abrera distrito 01,NaN,Renta neta media por persona,2023,16.682
2,08001 Abrera,0800101 Abrera distrito 01,0800101001 Abrera sección 01001,Renta neta media por persona,2023,16.065
3,08001 Abrera,0800101 Abrera distrito 01,0800101002 Abrera sección 01002,Renta neta media por persona,2023,15.216
4,08001 Abrera,0800101 Abrera distrito 01,0800101003 Abrera sección 01003,Renta neta media por persona,2023,19.616